language: objective-c
osx_image: xcode8.3
rvm:
    2.2.5

before_install:
    - gem install xcpretty
script:
    - xcodebuild test -project JSONSchema.xcodeproj -scheme JSONSchema -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3' | xcpretty -c 
